server.port=${PORT:8080}
# --- DataSource (Neon) ---
spring.datasource.url=jdbc:postgresql://ep-dawn-scene-ad04gl7v-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Yhatd97qCLNI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.headless=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

############  JWT #######################
jwt.expiration.minutes=1440
jwt.secret=8c192e95884a3cc0b8782aba1c27f70c184cc950dbbb78f31f82a085047117acdfe04ba3ec9dab9fc1b12b03eabbeb5b12e52881dfbfd67b1ccbdb2837d2afb393ff277ea2eb31c119e4299d30d780b129d8f51b0121b4835fb17ce9138106750a81ca0bdb80a2036f92a5618dbf14d524877f86ffa2ba1225a62e3dbffc93a616da3fd162ec99622c0311eb1c518ac3c5f47f95c97f65b08399190a626114ae4f0225f610397f20dfd74a36ac7b2ffb81d1c0307ae775d0fb9d70a620e7318fb21749940075dc0da596a518ef3a203567c8b50074ba27c01472f792a6323951ccafe7a58237860cdd0bb0a138b096ec8ba1eb28cb4439d785155c26dc01f5e2

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

########### MAIL #################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fabianmauriciosiza@gmail.com
spring.mail.password=huxefywupzkixyxg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

front.url=https://dataregister-web-1-0-0.onrender.com/verify/

server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB

aws.s3.region=us-east-2
aws.s3.bucket=dataregisterbucket
aws.s3.access-key=AKIAXVOWZMZFURZL72PL
aws.s3.secret-key=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

# === Redis Cloud ===
spring.data.redis.url=redis://default:paH0NGFBxXvjiKdaeon8YhZPgVg6fW06@redis-12849.c246.us-east-1-4.ec2.redns.redis-cloud.com:12849

# === Mercado Pago (Live) ===
mp.access-token=APP_USR-8348317426989478-102000-da07f677f12d09f36b637fc37e54cb8e-433549011
mp.public-key=APP_USR-c6b73a62-2c4d-4506-91fb-31294b265868
mp.currency=COP
mp.sandbox=true
mp.back-url=https://www.dataregisterapp.com/pay/return/success
mp.successUrl=https://www.dataregisterapp.com/pay/return/success
mp.pendingUrl=https://www.dataregisterapp.com/pay/return/pending
mp.failureUrl=https://www.dataregisterapp.com/pay/return/failure
mp.webhookUrl=https://www.dataregisterapp.com/pay/webhook